# 1. create a 3*3*3 array with random values 

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

# Print the random array
print(random_array)


[[[0.49803739 0.52184393 0.97198442]
  [0.20759299 0.11649374 0.07926312]
  [0.70315237 0.93173701 0.5232127 ]]

 [[0.29558181 0.93708311 0.15302356]
  [0.64615364 0.43933578 0.70914175]
  [0.85169194 0.1741202  0.75988347]]

 [[0.24290208 0.84199888 0.06557643]
  [0.97214594 0.81744342 0.14264378]
  [0.50872618 0.3687214  0.29783248]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, and 4 just below the diagonal
values = [1, 2, 3, 4]
for i in range(1, 5):
    matrix[i, i - 1] = values[i - 1]

# Print the resulting matrix
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with alternating 1s
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

# Print the resulting checkerboard matrix
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
mean = random_matrix.mean()
std_dev = random_matrix.std()
normalized_matrix = (random_matrix - mean) / std_dev

# Print the original and normalized matrices
print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.82371446 0.98034393 0.52835942 0.41596246 0.06484087]
 [0.6968814  0.59674286 0.06074115 0.62425011 0.90989303]
 [0.61960027 0.40309919 0.01605726 0.02187731 0.45097124]
 [0.33163866 0.43777244 0.26661857 0.80295109 0.70800384]
 [0.48935003 0.77771817 0.23089425 0.44787232 0.22351094]]

Normalized Matrix:
[[ 1.26241142  1.83301728  0.18642408 -0.22304143 -1.50218798]
 [ 0.80035474  0.43554703 -1.51712336  0.53575676  1.57636254]
 [ 0.51881727 -0.2699027  -1.67990814 -1.65870553 -0.09550337]
 [-0.53023559 -0.14358703 -0.76710574  1.18676984  0.84087415]
 [ 0.04431169  1.09484554 -0.8972505  -0.10679284 -0.92414811]]


# 5. How to find common values between two arrays ?

In [5]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

# Print the common values
print("Common values:", common_values)

Common values: [3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow ?

In [ ]:
# from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday's date
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


# 7. Consider two random array A and B, check if they are equal

In [9]:
import numpy as np

# Create two random arrays, A and B
A = np.random.rand(2, 5)
B = np.random.rand(2, 5)

# Check if the two arrays are equal
are_equal = np.array_equal(A, B)

# Print the result
if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector == max_value] = 0

# Print the original and modified vectors
print("Original vector:")
print(random_vector)


Original vector:
[0.13743918 0.69710558 0.79971015 0.         0.70654154 0.64678336
 0.83445601 0.76302129 0.39333795 0.02443071]


# 9. How to print all the values of an array?

In [11]:
import numpy as np

# Create an example array
my_array = np.array([1, 2, 3, 4, 5])

# Using a loop to print each value
for value in my_array:
    print(value)


1
2
3
4
5


In [12]:
import numpy as np

# Create an example array
my_array = np.array([1, 2, 3, 4, 5])

# Using print to display the entire array
print(my_array)


[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [18]:
import numpy as np

# Create a sample matrix
matrix = np.array([[11, 12, 13],
                   [24, 35, 26],
                   [7, 18, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
normalized_matrix = matrix - row_means

# Print the original and normalized matrices
print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix (Mean Subtracted from Each Row):")
print(normalized_matrix)


Original Matrix:
[[11 12 13]
 [24 35 26]
 [ 7 18  9]]

Normalized Matrix (Mean Subtracted from Each Row):
[[-1.          0.          1.        ]
 [-4.33333333  6.66666667 -2.33333333]
 [-4.33333333  6.66666667 -2.33333333]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [19]:
import numpy as np

# Create the main vector
main_vector = np.array([0, 1, 2, 3, 4, 5])

# Create the second vector with indices where you want to add 1
indices_to_add_1 = np.array([1, 3, 5])

# Create a mask to avoid repeated indices
mask = np.zeros_like(main_vector, dtype=bool)
mask[indices_to_add_1] = True

# Add 1 to the elements at the specified indices
main_vector[mask] += 1

# Print the modified vector
print(main_vector)


[0 2 2 4 4 6]


# 12.How to get the diagonal of a dot product?

In [20]:
import numpy as np

# Create two example matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
dot_product_result = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal_elements = np.diag(dot_product_result)

# Print the diagonal elements
print("Diagonal of the dot product:")
print(diagonal_elements)


Diagonal of the dot product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [21]:
import numpy as np

# Create a NumPy array (replace with your own array)
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Use numpy.unique to get unique values and their counts
unique_values, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[max_count_index]

print("Array:", arr)
print("Most frequent value:", most_frequent_value)

Array: [1 2 2 3 3 3 4 4 4 4]
Most frequent value: 4


# 14.How to get the n largest values of an array

In [22]:
import numpy as np

# Create a NumPy array (replace with your own array)
arr = np.array([4, 2, 7, 1, 9, 5, 8, 3, 6])

# Specify the number of largest values you want (e.g., n = 3)
n = 3

# Use numpy.partition to partially sort the array
# The n largest values will be on the right side of the partitioned array
partially_sorted = np.partition(arr, -n)

# Slice the last n elements to get the n largest values
n_largest_values = partially_sorted[-n:]

print("Array:", arr)
print(f"{n} Largest Values:", n_largest_values)

Array: [4 2 7 1 9 5 8 3 6]
3 Largest Values: [7 8 9]


# 15.How to create a record array from a regular array

In [24]:
import numpy as np

# Create a regular array with data
regular_array = np.array([(1, 'charan', 23),
                          (2, 'veera', 24),
                          (3, 'dada', 18)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Print the regular array
print("Regular Array:")
print(regular_array)

# Convert the regular array to a record array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

# Print the record array
print("\nRecord Array:")
print(record_array)

Regular Array:
[(1, 'charan', 23) (2, 'veera', 24) (3, 'dada', 18)]

Record Array:
((1, 'charan', 23), (2, 'veera', 24), (3, 'dada', 18))


# 16. How to swap two rows of an array?

In [25]:
import numpy as np

# Create a sample 2D NumPy array (replace with your own array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Indices of the rows you want to swap (0-based index)
row1_index = 0
row2_index = 2

# Swap the rows using array slicing and indexing
array[[row1_index, row2_index]] = array[[row2_index, row1_index]]

print("Array after swapping rows:")
print(array)

Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17.Write python code to reshape to the next dimension of numpy array?

In [26]:
import numpy as np

# Create the original 2D array
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape the array to the next dimension (3D)
reshaped_array = x.reshape((x.shape[0], x.shape[1], 1))

print("Original 2D Array:")
print(x)

print("\nReshaped 3D Array:")
print(reshaped_array)

Original 2D Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped 3D Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
