In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data = pd.read_excel("cars_train.xlsx")
data.head()

symboling  normalized.losses        make fuel.type aspiration num.of.doors  \
0          1              129.0       mazda       gas        std          two   
1          1              125.0  mitsubishi       gas        std         four   
2          3              150.0       mazda       gas        std          two   
3          3              194.0      nissan       gas        std          NaN   
4          0               85.0       honda       gas        std         four   

  body.style drive.wheels engine.location  wheel.base  ...  engine.size  \
0  hatchback          fwd           front        98.8  ...          122   
1      sedan          fwd           front        96.3  ...          122   
2  hatchback          rwd           front        95.3  ...           70   
3  hatchback          rwd           front        91.3  ...          181   
4      sedan          fwd           front        96.5  ...          110   

   fuel.system  bore  stroke compression.ratio horsepower  peak.rpm city.mpg  \
0         2bbl  3.39    3.39               8.6       84.0    4800.0       26   
1         2bbl  3.35    3.46               8.5       88.0    5000.0       25   
2         4bbl   NaN     NaN               9.4      101.0    6000.0       17   
3         mpfi  3.43    3.27               9.0      160.0    5200.0       19   
4         mpfi  3.15    3.58               9.0      101.0    5800.0       24   

   highway.mpg  Car_Price  
0           32    10595.0  
1           32     8189.0  
2           23    13645.0  
3           25    17199.0  
4           28    12945.0  

[5 rows x 26 columns]

In [2]:
print(data.describe())

        symboling  normalized.losses  wheel.base      length       width  \
count  162.000000         132.000000  162.000000  162.000000  162.000000   
mean     0.907407         123.060606   98.354321  173.595062   65.843210   
std      1.298855          36.144696    6.049384   12.339100    2.022325   
min     -2.000000          65.000000   86.600000  141.100000   60.300000   
25%      0.000000          94.000000   94.500000  166.425000   64.125000   
50%      1.000000         116.500000   96.500000  172.400000   65.450000   
75%      2.000000         150.000000  101.200000  181.650000   66.575000   
max      3.000000         256.000000  120.900000  208.100000   72.300000   

           height  curb.weight  engine.size        bore      stroke  \
count  162.000000   162.000000   162.000000  159.000000  159.000000   
mean    53.537654  2561.932099   128.160494    3.341698    3.239434   
std      2.346770   524.474870    41.684844    0.274566    0.356446   
min     47.800000  1488.000000 

In [3]:
data.isna().sum()

symboling             0
normalized.losses    30
make                  0
fuel.type             0
aspiration            0
num.of.doors         11
body.style            0
drive.wheels          0
engine.location       2
wheel.base            0
length                0
width                 0
height                0
curb.weight           0
engine.type           0
num.of.cylinders      2
engine.size           0
fuel.system           0
bore                  3
stroke                3
compression.ratio     0
horsepower            4
peak.rpm              4
city.mpg              0
highway.mpg           0
Car_Price             3
dtype: int64

In [4]:
data=data.fillna(method='bfill')
data.isna().sum()

symboling            0
normalized.losses    0
make                 0
fuel.type            0
aspiration           0
num.of.doors         0
body.style           0
drive.wheels         0
engine.location      0
wheel.base           0
length               0
width                0
height               0
curb.weight          0
engine.type          0
num.of.cylinders     0
engine.size          0
fuel.system          0
bore                 0
stroke               0
compression.ratio    0
horsepower           0
peak.rpm             0
city.mpg             0
highway.mpg          0
Car_Price            0
dtype: int64

In [5]:
data.head()

symboling  normalized.losses        make fuel.type aspiration num.of.doors  \
0          1              129.0       mazda       gas        std          two   
1          1              125.0  mitsubishi       gas        std         four   
2          3              150.0       mazda       gas        std          two   
3          3              194.0      nissan       gas        std         four   
4          0               85.0       honda       gas        std         four   

  body.style drive.wheels engine.location  wheel.base  ...  engine.size  \
0  hatchback          fwd           front        98.8  ...          122   
1      sedan          fwd           front        96.3  ...          122   
2  hatchback          rwd           front        95.3  ...           70   
3  hatchback          rwd           front        91.3  ...          181   
4      sedan          fwd           front        96.5  ...          110   

   fuel.system  bore  stroke compression.ratio horsepower  peak.rpm city.mpg  \
0         2bbl  3.39    3.39               8.6       84.0    4800.0       26   
1         2bbl  3.35    3.46               8.5       88.0    5000.0       25   
2         4bbl  3.43    3.27               9.4      101.0    6000.0       17   
3         mpfi  3.43    3.27               9.0      160.0    5200.0       19   
4         mpfi  3.15    3.58               9.0      101.0    5800.0       24   

   highway.mpg  Car_Price  
0           32    10595.0  
1           32     8189.0  
2           23    13645.0  
3           25    17199.0  
4           28    12945.0  

[5 rows x 26 columns]

In [6]:
 data=data[['wheel.base','length','width','height','curb.weight']]

In [7]:
data


wheel.base  length  width  height  curb.weight
0          98.8   177.8   66.5    53.7         2385
1          96.3   172.4   65.4    51.6         2405
2          95.3   169.0   65.7    49.6         2385
3          91.3   170.7   67.9    49.7         3071
4          96.5   175.4   65.2    54.1         2465
..          ...     ...    ...     ...          ...
157       114.2   198.9   68.4    56.7         3285
158        95.9   173.2   66.3    50.2         2811
159        91.3   170.7   67.9    49.7         3071
160        96.5   175.4   65.2    54.1         2465
161        93.3   157.3   63.8    55.7         2240

[162 rows x 5 columns]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Split data into train and test sets
x = data.iloc[:,:-1]
y = data.iloc[:,-1:]
print('x shape:\t',x.shape)
print()
print('Y shape:\t',y.shape)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Build a Linear Regression model
model = LinearRegression()
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict(x_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")


x shape:	 (162, 4)

Y shape:	 (162, 1)
Mean Squared Error: 61145.70771625056
R-squared: 0.7333830641805807


In [10]:
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_squared_error, r2_score

# Create Lasso model
lasso_model = Lasso(alpha=0.01)
lasso_model.fit(x_train, y_train)

# Make predictions with Lasso model
y_pred_lasso = lasso_model.predict(x_test)

# Evaluate the Lasso model
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("Lasso Model:")
print(f"Mean Squared Error: {mse_lasso}")
print(f"R-squared: {r2_lasso}")

# Create Ridge model
ridge_model = Ridge(alpha=0.01)
ridge_model.fit(x_train, y_train)

# Make predictions with Ridge model
y_pred_ridge = ridge_model.predict(x_test)

# Evaluate the Ridge model
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("\nRidge Model:")
print(f"Mean Squared Error: {mse_ridge}")
print(f"R-squared: {r2_ridge}")

Lasso Model:
Mean Squared Error: 61144.791359309645
R-squared: 0.7333870598213024

Ridge Model:
Mean Squared Error: 61143.70899621638
R-squared: 0.7333917793076269


In [13]:
# Build NB - Gaussian Model

from sklearn.naive_bayes import GaussianNB
gauss_nb = GaussianNB()
gauss_nb.fit(x_train,y_train)
print('Training Completed')
print()
ypred_gauss = gauss_nb.predict(x_test)
print('Predicted value is: \t',ypred_gauss)
print()
print('Testing completed')
print('='*75)
# Performance Measure
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
accuracy_gauss=accuracy_score(y_test,ypred_gauss)
print('*'*15 + 'Performance Measures on Gaussian Navie Bayes' + '*'*16)
print('Accuracy score:\t\n',accuracy_score(y_test,ypred_gauss))
print()
print('='*75)
print()
print('Confusion matrix:\t\n',confusion_matrix(y_test,ypred_gauss))
print()
print('='*75)
print()
print('Classification report is:\t\n',classification_report(y_test,ypred_gauss))
print()
print('='*75)

Training Completed

Predicted value is: 	 [2811 2385 3055 3042 2145 2337 2145 1889 2337 2380 1944 2976 2145 2536
 2385 2385 2403 2289 2037 3131 1900 2209 2385 2670 2811 3071 2658 3012
 2385 2340 3485 2414 2209]

Testing completed
***************Performance Measures on Gaussian Navie Bayes****************
Accuracy score:	
 0.09090909090909091


Confusion matrix:	
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Classification report is:	
               precision    recall  f1-score   support

        1889       0.00      0.00      0.00         0
        1900       0.00      0.00      0.00         0
        1905       0.00      0.00      0.00         1
        1918       0.00      0.00      0.00         1
        1944       0.00      0.00      0.00         0
        1971       0.00      0.00      0.00         1
        2010       0.00      0.00      0.00         1
        2024       0.00      0.00      0.00        

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Prec

In [16]:
#Build NB - Multinomial Model
from sklearn.naive_bayes import MultinomialNB
mul_nb = MultinomialNB()
mul_nb.fit(x_train,y_train)
print('Training Completed')
print()
ypred_mul_nb = mul_nb.predict(x_test)
print('Predicted value is: \t',ypred_mul_nb)
print()
print('Testing completed')
print('='*75)
#Performance Measure
accuracy_mul_nb=accuracy_score(y_test,ypred_mul_nb)
print('*'*14 + 'Performance Measures on Multinomial Navie Bayes' + '*'*14)
print('Accuracy score:\t\n',accuracy_score(y_test,ypred_mul_nb))
print()
print('='*75)
print()
print('Confusion matrix:\t\n',confusion_matrix(y_test,ypred_mul_nb))
print()
print('='*75)
print()
print('Classification report is:\t\n',classification_report(y_test,ypred_mul_nb))
print()
print('='*75)

Training Completed

Predicted value is: 	 [2385 2385 2465 2465 2385 2385 2145 2145 2385 2385 2145 2385 2145 2385
 2465 2465 2385 2145 2465 2385 2240 2465 2465 2145 2385 2385 2465 2385
 2465 2385 2465 2145 2465]

Testing completed
**************Performance Measures on Multinomial Navie Bayes**************
Accuracy score:	
 0.0


Confusion matrix:	
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Classification report is:	
               precision    recall  f1-score   support

        1905       0.00      0.00      0.00       1.0
        1918       0.00      0.00      0.00       1.0
        1971       0.00      0.00      0.00       1.0
        2010       0.00      0.00      0.00       1.0
        2024       0.00      0.00      0.00       1.0
        2145       0.00      0.00      0.00       0.0
        2190       0.00      0.00      0.00       1.0
        2212       0.00      0.00      0.00       1.0
        2221 

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Prec

In [17]:
# Build NB - Bernoulli Model
from sklearn.naive_bayes import BernoulliNB
ber_nb = BernoulliNB()
ber_nb.fit(x_train,y_train)
print('Training Completed')
print()
ypred_ber_nb = ber_nb.predict(x_test)
print('Predicted value is: \t',ypred_ber_nb)
print()
print('Testing completed')
print('='*75)
 #Performace Measure
accuracy_ber_nb=accuracy_score(y_test,ypred_ber_nb)
print('*'*15 + 'Performance Measures on Bernoulli Navie Bayes' + '*'*15)
print('Accuracy score:\t\n',accuracy_score(y_test,ypred_ber_nb))
print()
print('='*75)
print()
print('Confusion matrix:\t\n',confusion_matrix(y_test,ypred_ber_nb))
print()
print('='*75)
print()
print('Classification report is:\t\n',classification_report(y_test,ypred_ber_nb))
print()
print('='*75)

Training Completed

Predicted value is: 	 [2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145
 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145 2145
 2145 2145 2145 2145 2145]

Testing completed
***************Performance Measures on Bernoulli Navie Bayes***************
Accuracy score:	
 0.0


Confusion matrix:	
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Classification report is:	
               precision    recall  f1-score   support

        1905       0.00      0.00      0.00       1.0
        1918       0.00      0.00      0.00       1.0
        1971       0.00      0.00      0.00       1.0
        2010       0.00      0.00      0.00       1.0
        2024       0.00      0.00      0.00       1.0
        2145       0.00      0.00      0.00       0.0
        2190       0.00      0.00      0.00       1.0
        2212       0.00      0.00      0.00       1.0
        2221 

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Prec

# Ensemble Model
1. Bagging Classifier

In [18]:
#Baggingclassifier
from sklearn.ensemble import BaggingClassifier
bagc=BaggingClassifier(base_estimator=gauss_nb,n_estimators=5,random_state=2)
bagc.fit(x_train,y_train)#train the model
#test the model
ypred_bagc=bagc.predict(x_test)
print('*'*100)
print('Confusion Matrix:\n',confusion_matrix(y_test,ypred_bagc))
print('-'*100)
accuracy_bagc=accuracy_score(y_test,ypred_bagc)
print('Accuracy Score:\t',accuracy_bagc)
print('-'*100)
print('Classification Report:\n',classification_report(y_test,ypred_bagc))
print('='*100)

****************************************************************************************************
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
----------------------------------------------------------------------------------------------------
Accuracy Score:	 0.09090909090909091
----------------------------------------------------------------------------------------------------
Classification Report:
               precision    recall  f1-score   support

        1900       0.00      0.00      0.00         0
        1905       0.00      0.00      0.00         1
        1918       0.00      0.00      0.00         1
        1938       0.00      0.00      0.00         0
        1944       0.00      0.00      0.00         0
        1971       0.00      0.00      0.00         1
        2010       0.00      0.00      0.00         1
        2024       0.00      0.00      0.00         1
        20

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\naive_b

In [19]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rand_for=RandomForestClassifier(n_estimators=10,random_state=1)
rand_for.fit(x_train,y_train)#train the model
#test the model
ypred_rand=rand_for.predict(x_test)
print('*'*100)
print('Confusion Matrix:\n',confusion_matrix(y_test,ypred_rand))
print('-'*100)
accuracy_rand=accuracy_score(y_test,ypred_rand)
print('Accuracy Score:\t',accuracy_rand)
print('-'*100)
print('Classification Report:\n',classification_report(y_test,ypred_rand))
print('='*100)

****************************************************************************************************
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
----------------------------------------------------------------------------------------------------
Accuracy Score:	 0.06060606060606061
----------------------------------------------------------------------------------------------------
Classification Report:
               precision    recall  f1-score   support

        1900       0.00      0.00      0.00         0
        1905       0.00      0.00      0.00         1
        1909       0.00      0.00      0.00         0
        1918       0.00      0.00      0.00         1
        1971       0.00      0.00      0.00         1
        2004       0.00      0.00      0.00         0
        2010       0.00      0.00      0.00         1
        2024       0.00      0.00      0.00         1
        20

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Pr

In [20]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rand_for_1=RandomForestClassifier(n_estimators=10,random_state=1,max_depth=2)
rand_for_1.fit(x_train,y_train)#train the model
#test the model
ypred_rand_1=rand_for_1.predict(x_test)
print('*'*100)
print('Confusion Matrix:\n',confusion_matrix(y_test,ypred_rand_1))
print('-'*100)
accuracy_rand_1=accuracy_score(y_test,ypred_rand_1)
print('Accuracy Score:\t',accuracy_rand_1)
print('-'*100)
print('Classification Report:\n',classification_report(y_test,ypred_rand_1))
print('='*100)

****************************************************************************************************
Confusion Matrix:
 [[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
----------------------------------------------------------------------------------------------------
Accuracy Score:	 0.030303030303030304
----------------------------------------------------------------------------------------------------
Classification Report:
               precision    recall  f1-score   support

        1905       0.00      0.00      0.00         1
        1918       0.00      0.00      0.00         1
        1945       0.00      0.00      0.00         0
        1971       0.00      0.00      0.00         1
        1989       0.00      0.00      0.00         0
        2010       0.00      0.00      0.00         1
        2024       0.00      0.00      0.00         1
        2145       0.00      0.00      0.00         0
        2

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Pr