In [1]:
import numpy as np

# Reward Matrix

In [2]:
R=np.matrix([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100]])
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

# Construct the zero matrix of the size of R matrix to form the Q matrix

In [3]:
Q=np.matrix(np.zeros([6,6]))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Define gamma value - Learning Parameter

In [4]:
gamma=0.8

# Q- Learning:
 Q(state,action)= R(state,action) + gamma * Max(Q(next state,all actions))

In [5]:
initial_state=1

# Define the available action function

In [6]:
def available_actions(state):
    current_state_row=R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [7]:
available_act=available_actions(initial_state)
print(available_act)

[3 5]


In [8]:
#sample next action function
def sample_next_action(available_actions_range):
    next_action=int(np.random.choice(available_act,1))
    return next_action

In [9]:
action=sample_next_action(available_act)
print(action)

5


# Q Matrix-update function

In [10]:
def update(current_state,action,gamma):
    max_index=np.where(Q[action,]==np.max(Q[action,]))[1] 
    if max_index.shape[0]>1:
        max_index=int(np.random.choice(max_index,size=1))
    else:
        max_index=int(max_index)
        max_value=Q[action,max_index]
        Q[current_state,action]=R[current_state,action]+gamma*max_value

# Train the agent with this environment information

In [ ]:
for i in range(10000000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    action=sample_next_action(available_act)
    update(current_state,action,gamma)

# Testing
 goal_state=5

In [ ]:
current_state=4
steps=[current_state]
while current_state!=5:
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index=int(np.random.choice(next_step_index,size=1))
    else:
        next_step_index=int(next_step_index)
    steps.append(next_step_index)
    current_state=next_step_index
print('Optimum path of initail state {} to the Goal State is {}'.format(initial_state,step)